### ISSUE TITLE
Issues with show_hidden and hidden folders

### ISSUE THREAD

**Issue by meain** [rabite0/hunter#20]
There are a few issues with the `show_hidden` implementation from what I can tell.

- I don't think that the config flag is doing anything. I was unable to use to use to show hidden files. ( I did sone testing, I feel like the config file is not being read )
- `h` which should be toggling the hidden files actually is overridden by the vim `h` mapping. I am guessing `l` has the same problem too.
- If in a folder in a hidden dir (I am guessing without show_hidden enabled) if you try to go back since there is no listed files, it errors out.

#### Backtrace
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/bc44841ad2a2ad5f6c5e67b9e35ed8e7e71d4dc7/src/libcore/slice/mod.rs:2539:10
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: hunter::die_gracefully::{{closure}}
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::continue_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::panicking::panic_bounds_check
  10: hunter::file_browser::FileBrowser::cache_files
  11: <hunter::file_browser::FileBrowser as hunter::widget::Widget>::refresh
  12: <hunter::file_browser::FileBrowser as hunter::widget::Widget>::on_key
  13: hunter::widget::Widget::handle_input
  14: hunter::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
```

![](https://i.imgur.com/OEkv2at.png)
The error triggers if I go back one more step. I started hunter in the folder `~/.config/hunter`

**Comment by rabite0** [comment]
Oh crap, that's not good :(

You're right, the toggle_hidden mapping was on h, but since movement is matched before that, it never happens. I pushed a fix for that. It's now mapped to "H". I'm not sure if that's the best choice though.. What do you think?

I have to admit, I don't really use the vi-bindings so they're not tested as well as they probably should.

The show_hidden setting works for me, are you sure you spelled it right? It has to be "show_hidden=off", although spaces in between should be ok, if I remember right. Does "animation=off" do anything? Maybe it can't find the file, is there anything in the log? (Press "L").

And that crash.. ugh, that's really bad. I will fix that soon.

Thanks for reporting.

**Comment by rabite0** [comment]
Ok, right, "L" should be open_bg, analogous to how "F" with the emacs-bindings. "g" opens the log now with vi-bindings.

Btw, open_bg actually doesn't work as it should right now. It only works on executables, but it should also work on other kind of files and open them in the background.

**Comment by meain** [comment]
- For the `show_hidden` toggle, ranger uses a command `:set show hidden` or something like that. But there is this another one called [`lf`](https://github.com/gokcehan/lf). It uses a key combination of `zh` to toggle hidden files. You could probably use something like this. `H` might be a bit confusing as we have `J` and `K` do page up and page down respectively.

- I did some testing and I don't think the config is getting loaded.
I have a wild guess that this might be because the crate `dirs-2` cannot read `$XDG_CONFIG` as it is not set on my **mac** machine.  I did try modifying the code directly for the config flags and that works though. So it should be the file reading logic that has some issues.

**Comment by rabite0** [comment]
Oh, I didn't realize you're on macOS!

Yeah, that might be the reason. I was under the impression that dirs-2 handles this gracefully, resorting to some kind of fallback directory if those environment variables aren't set.

The docs say it resolves to "$HOME/Library/Preferences", so hunter would, or should be looking for  "$HOME/Library/Preferences/hunter/config"

I definitely want to get first-class macOS support, but it's hard without a mac ;). I'm probably going to install it in a VM to iron out the issues.

**Comment by rabite0** [comment]
And yes, key bindings are a real sore point right now. Those need a complete overhaul. I want to make them configurable eventually, but I still need to think of a way to implement it (read: hack away at it until it works and looks nice ;) )

**Comment by meain** [comment]
Hmm, it is unusual to have configs at `$HOME/Library/Preferences`. I think most people would prefer it at `~/.config/hunter`.  Most of the other tools I have used seems to just use `~/.config/` itself.

**Comment by meain** [comment]
> hack away at it until it works and looks nice

Pretty much every software project.

You could probably find some inspiration from how [lf](https://github.com/gokcehan/lf) does keybindings for the vim part.

**Comment by rabite0** [comment]
See: https://github.com/Larusso/dirs-rs

I don't know why it's like that, but apparently it's adhering to some Apple guidelines. I could easily hardcode it do ~/.config/hunter though. Just to clarify, that's not what most other (unixy/terminaly) tools do?

**Comment by meain** [comment]
No, most of them just use `~/.confg` itself. I times I have seen them use home dir, but that is usually it.

This is all the stuff in my `~/.config` dir.
![](https://i.imgur.com/KUheFH1.png)

**Comment by rabite0** [comment]
Ok, I pushed a fix, but since I can't test it, I'm not sure if it works.

**Comment by meain** [comment]
Which branch, I didn't see any updates on master. I could test it out for you.

**Comment by rabite0** [comment]
On "mac-fix". master doesn't even work on mac unless i screwed up and merged those branches.

**Comment by meain** [comment]
No, I don't think that fixed it. I do not think that it is reading the config.

Let me see if I can send you a PR some time tomorrow on this.

**Comment by meain** [comment]
I even tried this

```rust
pub fn hunter_path() -> HResult<PathBuf> {
    let mut hunter_path = if cfg!(mac_os) {
        PathBuf::from("~/.config/").canonicalize()?
    } else {
        dirs_2::config_dir()?
    };
    hunter_path.push("hunter/");
    Ok(PathBuf::from("~/.config/hunter").canonicalize()?)
}
```

But for some reason it still fails to work. I am confused as to what is happening.

**Comment by rabite0** [comment]
Interesting. Some people had issues related to the thread pool, which made hunter crash. I assumed it was due to some differences between Linux/macOS, but maybe it's actually something else..

BTW, I did it wrong. It's supposed to be "cfg!(macos)". I already pushed a new version. It also prints the directory to stderr, so start it with hunter 2> dbg.txt or something like that. It will then print the directory it's looking for.

**Comment by meain** [comment]
Well, I did not see anything in related to the directory but I found this `reset: standard error: Inappropriate ioctl for device`.

**Comment by rabite0** [comment]
BTW, I did it wrong. It's supposed to be "cfg!(macos)". I already pushed a new version. It also prints the directory to stderr, so start it with hunter 2> dbg.txt or something like that. It will then print the directory it's looking for.

If it doesn't print anything it's not working...

Weird that it doesn't work even if you hardcode that path. I can only image that there's something fishy in config.rs, when it checks for the file with 

if !config_path.exists() {        
   return Ok(Config::new());
}

But that shouldn't be a problem if the file exists... Other that that it just uses read_to_string.

So when Config::load runs it just gets the path from paths::config_path() and then reads the contents with read_to_string(). Nothing else going on there.

IDK, I'm going to check this out tomorrow when I have a macOS VM.

Anyway, thanks for working this through with me.

**Comment by meain** [comment]
Glad I could you out.

One more thing. When I was trying out something earlier, I think I found that the `load` function (in `config.rs` ) was not getting called. But then I saw it was working for you, I dropped that though.

 But I think it might have some errors somewhere and so it might not be calling `load`, only on macOS.

You might wanna check in that direction.

**Comment by rabite0** [comment]
Hmm.. well the config is loaded asynchronously to speed up the starting process. This might be related to the threading issues someone had on macros.

I'll probably start by making that synchronous. Then it's going to be obvious why loading fais.

Thanks!

**Comment by rabite0** [comment]
Unfortunately I was unable to install macOS on VirtualBox.. I'm going to try with a preinstalled image, but if that doesn't work either, IDK. Since the only problem seems to be that it doesn't load the configuration it's not too pressing of an issue anyway. Just wondering: It doesn't load the config at all, right? Not even under $HOME/Library/Preferences?

Anyway, onto fixing the crash :).

**Comment by rabite0** [comment]
Crash should be fixed now. This could always happen when the directory became empty due to only containing hidden files.

**Comment by meain** [comment]
Yup, it does read the config when put inside `$HOME/Library/Preferences`.

**Comment by rabite0** [comment]
Great. Since the crash and keybind issues are fixed I'm closing this issue. I'll see what I can do about the config location when I can get a macOS VM running, but since it's working and at least *technically* correct I don't really consider it a bug. If you disagree and are willing to test a few iterations in case I can't get a VM running feel free to open a new issue for that.

Anyway, thanks for reporting and working with me on this.
