### ISSUE TITLE
Mouse events causes weird behavior

### ISSUE THREAD

**Issue by Mart-Bogdan** [rabite0/hunter#32]
When I move the mouse over the terminal window and touch scroll, or click mouse buttons, program start behaving strangely.
![image](https://user-images.githubusercontent.com/775038/57096876-ef22ea00-6d1e-11e9-8f2b-c36050f57f79.png)
1) 3 weird blue vertical bars are rendered between main panels. On each event, bar grows!
2) On left bar some random symbols appears, `U`,`D`,`)`,`’`
3) Above the right bar, several `\` are rendered

Also, annoying event shows up on the bottom, that says me to not use the mouse, but this I could ignore.

I'd suggest just disable terminal mouse events, so users could use mouse for simply selecting the text, to be copied elsewhere.

**Comment by rabite0** [comment]
I disabled mouse support for now since it's not used anyway.

Does that fix the glitched drawing? 

That actually looks like it's printing an error message to the screen, which is then drawn over. Since I've never seen it print error messages due to unused mouse input I'm not sure if that's enough to fix the issue. If it persists, could you try starting hunter with "hunter 2> debug.txt" and paste the contents?

**Comment by Mart-Bogdan** [comment]
Hello, debug.txt is empty, 0 bites
```
winnie@winnie-Latitude-E6420:~$ hunter 2>debug.txt
winnie@winnie-Latitude-E6420:~$ less debug.txt 
winnie@winnie-Latitude-E6420:~$ less debug.txt 
winnie@winnie-Latitude-E6420:~$ cat debug.txt 
winnie@winnie-Latitude-E6420:~$ 
```
and furthermore, when I use less to view debug.txt (`less debug.txt`) i've got blue screen background:
![image](https://user-images.githubusercontent.com/775038/57241392-877be000-7039-11e9-9918-6f59e48afb9a.png)
If I resize terminal without less, and open less -- again blue screen.
If I resize a virtual terminal with less opened, it resets the screen to the black background.
![image](https://user-images.githubusercontent.com/775038/57241466-babe6f00-7039-11e9-80b4-66d8c270341e.png)
I've exited hunter with q key.
Actually, this happens no matter if I redirected stderr. Seems hunter messes with terminal, not restoring it after exit.

**Comment by rabite0** [comment]
Does it still draw crap when it receives mouse events or is this a different problem? What terminal is that? gnome-terminal? I'll test that one. I hope I get the same problem :).

Could you maybe try with xterm or some other terminal to see if it happens there, too? There have been mixed reports with this in the past.

I just re-enabled a call to "reset" when hunter quits. This is ugly, but it should fix the resetting in the mean-time.

**Comment by Mart-Bogdan** [comment]
Thanks @rabite0, tryed 1.1.2 and mouse issue go away.

Less issue still persist. I'm using Konsole from KDE 5 (Konsole 17.12.3)

Tryed in xterm, there is small issue with coloring, but not whole screen.

In GNOME Terminal all seems clear.

Strange. 0_O

**Comment by Mart-Bogdan** [comment]
on xterm only status line of **less** is blue
![image](https://user-images.githubusercontent.com/775038/57261997-f6295f80-7072-11e9-8c1b-31401f95f0a1.png)
on Konsole whole screen
![image](https://user-images.githubusercontent.com/775038/57262025-1822e200-7073-11e9-9370-507a42edf74a.png)
Weird, I thought all terminals are identical in terms of VT specification :-(

**Comment by Mart-Bogdan** [comment]
And I confirm that original bug (after checking out the previous version of Hunter)  is reproducing only in Konsole, perhaps bug should be filed there?

**Comment by Mart-Bogdan** [comment]
UPD.  
Konsole + tmux = no bug (both)
Konsole + GNU Screen = slight color glitch after exit, and screen not gets leared/restored, but no errors after that. Seems satisfyingly.
![image](https://user-images.githubusercontent.com/775038/57262332-47861e80-7074-11e9-9380-805c3e4c27b0.png)

**Comment by rabite0** [comment]
I completely revamped terminal resetting in the newest version. That should hopefully mostly fix these issues.

And yes, for some reason squeezing tmux in between often fixes many drawing glitches like this. It probably filters/rewrites escape codes on the fly. The most extreme example is Emacs's ansi-term. Without tmux hunter is totally glitched, but with tmux it's drawing perfectly fine, just unusably slow. urxvt also has some slight issues without tmux, but nothing major. Oh well, I'll get to that eventually.

Anyway, thank you for taking your time to all this testing. The information has been very valuable.
